Nismed V0.2/NISMed/NISMed/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views
#from django.contrib.auth.views import login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth import views as auth_views



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^administracion_turnos/', include('administracion_turnos.urls')),
    url(r'^administracion_pacientes/', include('administracion_pacientes.urls')),
    url(r'^administracion_usuarios/', include('administracion_usuarios.urls')),
    url(r'^administracion_informes/', include('administracion_informes.urls')),
    url(r'^administracion_reperfusion/', include('administracion_reperfusion.urls')),

    url(r'^$', auth_views.login, {'template_name':'login.html'}, name = 'login'),
    url(r'^logout/$', auth_views.logout, {'next_page':'login'}, name = 'logout'),
     url(r'^cuenta/', views.cuenta, name='cuenta'),





]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Nismed V0.2/NISMed/administracion_turnos/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from administracion_pacientes.models import *
from administracion_usuarios.models import *
#from django.utils import timezon

# Create your models here.






class turno(models.Model):
	#claves foraneas----------------------------------------------------------------------------------------------------------
	medico= models.ManyToManyField(medico,blank = True,null = True)
	# creador= models.ManyToManyField(usuario, blank = True, null = True)
	#Lista de selección--------------------------------------------------------------------------------------------------------
	ESTADO = (
		('activo','Activo'),
		('cerrado','Cerrado'),
		('desfasado','Desfasado'),
		)
	UNIDAD = (
		('turno', 'Turno'),
		('sala', 'Sala'),

	)

	#atributos----------------------------------------------------------------------------------------------------------------
	fechaInicio = models.DateField(blank=True,null = True) # formato DD MM AAAA
	fechaTermino =models.DateField(blank=True,null = True)
	estado = models.CharField(max_length =20,choices=ESTADO,default = 'activo')
	unidad = models.CharField(max_length =20,choices=UNIDAD)



#class turnoMedico(models.Model):
	#claves foraneas----------------------------------------------------------------------------------------------------------
	#medico= models.ForeignKey(medico,blank = True,null = True)
	#turno= models.ForeignKey(turno,blank = True,null = True)

	#Lista de selección--------------------------------------------------------------------------------------------------------


	#atributos----------------------------------------------------------------------------------------------------------------

	#rol = (max_length = 2,choices=ESTADO)



class resumen(models.Model):
	#claves foraneas----------------------------------------------------------------------------------------------------------
	turno= models.ForeignKey(turno,blank = True,null = True)


	#atributos----------------------------------------------------------------------------------------------------------------
	ingresosSala =  models.IntegerField()
	clavesStroke = models.IntegerField()
	trombolisis  = models.IntegerField()
	trombectomias  = models.IntegerField()
	interconsultasUEA = models.IntegerField()
	interconsultasOtroServicios = models.IntegerField()
	controles = models.IntegerField()
	controlesMCM = models.IntegerField()
	altasSala = models.IntegerField()
	observacion = models.TextField()



#pensar si sacar estado a una entidad sola por temas de historial del estado y traspaso

class hospitalizacionTurno(models.Model):
	#claves foraneas----------------------------------------------------------------------------------------------------------
	turno= models.ForeignKey(turno,blank = True,null = True)
	evento = models.ForeignKey(evento,blank = True,null = True )
	#Lista de selección--------------------------------------------------------------------------------------------------------

		#MEJORAR ESTADO
	ESTADO = (
		('vigente','Vigente'),
		('finalizado','Finalizado'),

		)
	#claves foraneas----------------------------------------------------------------------------------------------------------


	fechaInicio = models.DateField(blank=True,null = True) # formato DD MM AAAA
	fechaTermino =models.DateField(blank=True,null = True) # formato DD MM AAAA
	estado = models.CharField(max_length = 20,choices=ESTADO,blank=True,null = True, default = 'vigente')




class control(models.Model):
	#claves foraneas----------------------------------------------------------------------------------------------------------
	hospitalizacion= models.ForeignKey(hospitalizacionTurno,blank = True,null = True)
	#Lista de selección--------------------------------------------------------------------------------------------------------
	#MEJORAR ESTADO

	UBICACION = (
			('UMA','Activo'),
			('transferido','trasferico'),
			('alta','Alta'),
			)

	ESTADO = (
			('vigente','Vigente'),
			('transferido','Transferido'),
			('alta','alta'),
			)

	RANKIN = (
		(0,'0'),
		(1,'1'),
		(2,'2'),
		(3,'3'),
		(4,'4'),
		(5,'5'),
		(6,'6'),
			)
	GLASGOW = (
		(3,'3'),
		(4,'4'),
		(5,'5'),
		(6,'6'),
		(7,'7'),
		(8,'8'),
		(9,'9'),
		(10,'10'),
		(11,'11'),
		(12,'12'),
		(13,'13'),
		(14,'14'),
		(15,'15'),
				)
	NIHSS = (
		(0,'0'),
		(1,'1'),
		(2,'2'),
		(3,'3'),
		(4,'4'),
		(5,'5'),
		(6,'6'),
		(7,'7'),
		(8,'8'),
		(9,'9'),
		(10,'10'),
		(11,'11'),
		(12,'12'),
		(13,'13'),
		(14,'14'),
		(15,'15'),
		(16,'16'),
		(17,'17'),
		(18,'18'),
		(19,'19'),
		(20,'20'),
		(21,'21'),
		(22,'22'),
		(23,'23'),
		(24,'24'),
		(25,'25'),
		(26,'26'),
		(27,'27'),
		(28,'28'),
		(29,'29'),
		(30,'30'),
		(31,'31'),
		(32,'32'),
		(33,'33'),
		(34,'34'),
		(35,'35'),
		(36,'36'),
		(37,'37'),
		(38,'38'),
		(39,'39'),
		(40,'40'),
		(41,'41'),
		(42,'42'),
		(43,'43'),
		(44,'44'),
		(45,'45'),

				)



	#atributos-----------------------------------------------------------------------------------------------------------------
	primer =models.CharField(max_length = 3, default= 'no')
	ubicacion= models.CharField(max_length = 100)
	cama = models.IntegerField()

	fecha = models.DateField(blank=True,null = True)

	antecedentesHistoria =models.TextField()
	examenFisico= models.TextField()
	labImagenes = models.TextField()
	diagnostico = models.TextField()
	estado = models.CharField(max_length = 20,choices=ESTADO,blank=True,null = True, default= 'vigente')
	planesPendiente = models.TextField(blank=True,null = True)
	rankinScale = models.IntegerField(choices = RANKIN)
	glasgowScale = models.IntegerField(choices = GLASGOW)
	nihssScale = models.IntegerField(choices = NIHSS)



class revision(models.Model):
	#claves foraneas----------------------------------------------------------------------------------------------------------
	control= models.ForeignKey(control,blank = True,null = True)
	#Lista de selección--------------------------------------------------------------------------------------------------------

	REVISION = (
		('hoy','Hoy'),
		('24hrs','24 hrs'),
		('48hrs','48 hrs'),
		('SOS','SOS'),
		)
	#claves foraneas----------------------------------------------------------------------------------------------------------


	fecha = models.DateTimeField(blank=True,null = True) # formato DD MM AAAA

	revision = models.CharField(max_length = 20,choices=REVISION,blank=True,null = True)

Nismed V0.2/NISMed/templates/turno/crear_planes.html
{% extends "base_popup.html" %}
{% block title %}Nuevo plan y oendiente{% endblock %}
{% block content %}

<form action="." method="POST">{% csrf_token %}

  <hr>
  <div class= "row ">
  <div class="col-sm-1 btn">
  </div>
  <i class="fas fa-user fa-3x"></i> &nbsp;&nbsp;&nbsp;&nbsp; <h1>{{Control.hospitalizacion.paciente.nombres}} {{Control.hospitalizacion.paciente.primerApellido}}</h1>
  </div>
  <hr>
{{form.errors}}

<div class= "row ">
        <div class="col-sm-5 btn" >
          <h3 style="background-color:lightblue">Plan y pendiente</h3>
        </div>
          <div class="col-sm-1 btn">

          </div>
          <div class="col-sm-2 btn">


          </div>

          <div class="col-sm-2 " >

          </div>

          <div class="col-sm-2 btn">

          </div>



</div>





  <div class= "row ">
          <div class="col-sm-1 btn" >

          </div>
            <div class="col-sm-1 btn">
                <label>Detalle</label>
            </div>
            <div class="col-sm-2 btn">
                {{form.planesPendiente}}

            </div>

            <div class="col-sm-1 " >

            </div>

            <div class="col-sm-2 btn">
                {{form.planesPendiente.errors}}
            </div>


  </div>

<div style="display: none; ">
    {{form.antecedentesHistoria}}
        {{form.examenFisico}}
  {{form.labImagenes}}
  {{form.rankinScale}}
  {{form.glasgowScale}}
  {{form.diagnostico}}
{{form.ubicacion}}
{{form.fecha}}
{{form.primer}}
{{form.estado}}
{{form.nihssScale }}
{{form.cama}}

{{form.hospitalizacion}}
 </div>



<br>
<br>


<div class="row">
  <div class="col-9"></div>
  <div class="col-3"><input class="btn btn-primary" type="submit" value="Submit" /></div>


 </div>


</form>

 {% endblock %}

Nismed V0.2/NISMed/templates/turno/crear_revision.html
{% extends "base_popupR.html" %}
{% block title %}Nueva turno{% endblock %}
{% block content %}

<form action="/administracion_turnos/crear_revision/" method="POST">{% csrf_token %}

  <hr>
  <div class= "row ">

  <div class="col-sm-1 btn">
  <h5>Crear revisión</h5>
</div>
  </div>
  <hr>

  <div class= "row ">


            <div class="col-sm-1 btn">
                <label>Realizar revisión en</label>
            </div>
            <div class="col-sm-2 btn">
                {{form.revision}}

            </div>







</div>



<div class= "row ">
        <div class="col-sm-2 btn">
      {{form.revision.errors}}

          </div>
          <div class="col-sm-2 btn">


          </div>

          <div class="col-sm-2 " style="display: none;" >

            {{form.control}}


          </div>

          <div class="col-sm-2 btn">

          </div>



</div>




<input class="btn btn-primary" type="submit" value="Submit" />





</form>

 {% endblock %}

Nismed V0.2/NISMed/templates/turno/home_turno.html
{% extends "base_turno.html" %}
{% load mathfilters %}





{% block title %}Home Turno{% endblock %}
{% block content %}
<hr>
<div class= "row ">
<div class="col-sm-1 btn">
</div>
<h1>Home turno</h1>
</div>
<hr>
<br>
{% if Turno %}


<div class="container-fluid">
<div class="row">

    <div class="col-1">
   <a href="{% url "crear_hospitalizacion"  %} " title= "Hospitalizar paciente"> <i class="fa fa-user-plus fa-5x" aria-hidden="true"></i></a>
</div>
  <div class="col-5">



  </div>
  <div class="col-1">
 <a href="{% url "home_turno"  %} " title= "Refrescar"> <i class="fa fa-undo-alt fa-5x" aria-hidden="true"></i></a>
</div>
<div class="col-4">
  <h2> Fecha de inicio del turno: {{Turno.0.fechaInicio}} </h2>    <h2> Fecha de hoy: {{hoy}} </h2>
</div>
</div>
</div>





<br>
<br>
<div class="container-fluid">

<table id="table_id" class="display">
    <thead>
        <tr>

          <th style="text-align: center">Fecha</th>
            <th style="text-align: center">Paciente</th>
            <th style="text-align: center" >RUT</th>
            <th style="text-align: center" >Días desde 1era evaluacion</th>
            <th style="text-align: center" >Ubicación</th>
            <th style="text-align: center" >Cama</th>
            <th style="text-align: center" >Antecedentes e historia</th>
            <th style="text-align: center" >Exámen físico</th>
            <th style="text-align: center" >Lab imágenes</th>
            <th style="text-align: center" >Diagnóstico</th>
            <th style="text-align: center" >Planes y pendientes</th>
            <th style="text-align: center" >Estado</th>
            <th style="text-align: center" >Opciones</th>

        </tr>
    </thead>
    <tbody>

  {% if Hospitalizacion %}
             {% for i in Hospitalizacion %}

        <tr>

  <td style="text-align: center">{{i.fechaInicio}} </td>

            <td style="text-align: center">{{i.evento.paciente.nombres}} {{i.evento.paciente.primerApellido}} {% if i.evento.paciente.segundoApellido %} {{i.evento.paciente.segundoApellido}}  {% endif %}</td>

            <td style="text-align: center">{% if i.evento.paciente.RUT %} {{i.evento.paciente.RUT}}-{{i.evento.paciente.DV}}{% else %} <font style = "color: red"> dato faltante </font> {% endif %}</td>

            <td style="text-align: center" >
                {% if i.control_set.all.0 %}
              {% with i.control_set.all|dictsort:"fecha" as control %}
                {% if control.0.primer != hoy %}
                 {{ hoy | sub:control.0.fecha }}
                {% else %}
                Primer control realizado el día de hoy
                 {% endif %}

                {% endwith %}

                 {% endif %}
            </td>

            <td style="text-align: center">

              {% if i.control_set.all.0 %}

               {{ i.control_set.all.last.ubicacion }}

               {% endif %}

              </td>
              <td style="text-align: center">

                {% if i.control_set.all.0 %}

                 {{ i.control_set.all.last.cama }}

                 {% endif %}

                </td>
            <td style="text-align: center" >
              {% if i.control_set.all.0 %}

               {{ i.control_set.all.last.antecedentesHistoria }}

              {% endif %}

             </td>
            <td style="text-align: center" >

              {% if i.control_set.all.0 %}

               {{ i.control_set.all.last.examenFisico }}

              {% endif %}

            </td>
            <td style="text-align: center" >

              {% if i.control_set.all.0 %}

               {{ i.control_set.all.last.labImagenes }}

              {% endif %}
            </td>
            <td style="text-align: center" >
              {% if i.control_set.all.0 %}

               {{ i.control_set.all.last.diagnostico }}

              {% endif %}
            </td>
            <td style="text-align: center" >
              {% if i.control_set.all.0 %}

              {% if i.control_set.all.last.planesPendiente  %}  {{ i.control_set.all.last.planesPendiente }}{% else %} <font style = "color: red"> No posee planes y pendientes </font> {% endif %}


              {% endif %}
            </td>


              {% if i.control_set.all.0 %}

              <td style="text-align: center" >

                        {% if i.control_set.last.fecha == hoy %}
                              <font color = "green">  <i  title= "Posee control el día de hoy" class="fas fa-eye"></i></font>


                        {% else %}
                              <font color = "red"><i  title= "No posee control el día de hoy" class="fas fa-eye-slash"></i></font>
                         {% endif %}

                         {% with i.control_set.last as c%}
                             {% if c.revision_set.all.0 %}


                                       {% if c.revision_set.last.revision == 'SOS' %}

                                              <font color = "red"><i title= "SOS" class="fas fa-undo-alt"></i> SOS </fount>

                                        {% elif c.revision_set.last.revision == "hoy" %}

                                                <font color = "green"><i title= "Revisar hoy" class="fas fa-undo-alt"></i> hoy </fount>

                                        {% elif c.revision_set.last.revision == '24hrs' %}

                                              <font color = "blue"><i title= "Revisar en 24 hrs" class="fas fa-undo-alt"></i> 24 hrs</fount>

                                        {% elif c.revision_set.last.revision == '48hrs' %}

                                               <font color = "grey"><i title= "Revisar en 48 hrs" class="fas fa-undo-alt"></i> 48 hrs</fount>



                                        {% endif %}




                                        {% if c.revision_set.last.fecha.date  < ahora.date %}

                                        <font color = "red"><i class="fas fa-exclamation-circle"></i> Caducado </font>

                                        {% else  %}

                                            {% if c.revision_set.last.fecha.time  < ahora.time %}
                                                  <font color = "red"><i class="fas fa-exclamation-circle"></i> Caducado </font>

                                            {% endif %}






                                        {% endif %}










                             {% else %}

                               <font color = "black"><i title= "No posee estado de revisión" class="far fa-clock"></i></fount>

                             {% endif %}

                        {% endwith %}








            </td>



                       <td style="text-align: center" >
                         <a href="{% url "listar_control" i.id  %} " title= "Lista de controles">   <i class="fas fa-clipboard-list"></i> </a>
                         / <a href="{% url "crear_control" i.id  %} " title= "Crear control"> <i class="far fa-plus-square"> </i> </a>


                         {% with i.control_set.last as c %}

                         / <a title="Revisar control" href="" onclick="return popitupR('{% url "crear_revision" c.id %}')"><i class="far fa-clock"></i></a>
                         {% endwith %}



                       </td>

            {% endif %}




        </tr>

        {% endfor %}


       {% endif %}


    </tbody>
    <tfoot>
        <tr>
          <th style="text-align: center" >Fecha</th>
          <th style="text-align: center" >Paciente</th>
          <th style="text-align: center" >RUT</th>
          <th style="text-align: center" >Días desde 1era evaluacion</th>
          <th style="text-align: center" >Ubicación</th>
          <th style="text-align: center" >Cama</th>
          <th style="text-align: center" >Antecedentes e historia</th>
          <th style="text-align: center" >Exámen físico</th>
          <th style="text-align: center" >Lab imágenes</th>
          <th style="text-align: center" >Diagnóstico</th>
          <th style="text-align: center" >Planes y pendientes</th>
          <th style="text-align: center" >Estado</th>
          <th style="text-align: center" >Opciones</th>
        </tr>
    </tfoot>

</table>


</div>

{% else %}

<div class="container-fluid">
<div class="col-12">
<div class="row"> <h1>Lo sentimos, no se encuentra registro de turno activo, por favor cree un nuevo turno </h1></div>
</div>
</div>

{% endif %}








<!-- Button trigger modal -->
<!--  Launch demo modal
</button>-->

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>











 <script type="text/javascript">



  $(document).ready( function () {
    $('#table_id').DataTable(

      {
                  "language":{
                      "lengthMenu":"Mostrar _MENU_ registros por página.",
                      "zeroRecords": "Lo sentimos, no se han registrado hospitalizaciones dentro del turno.",
                      "info": "Mostrando página _PAGE_ de _PAGES_",
                      "infoEmpty": "No se ha encontrado coincidencia.",
                      "infoFiltered": "(filtrados de un total de _MAX_ registros)",
                      "search" : "Buscar",
                      "LoadingRecords": "Cargando ...",
                      "Processing": "Procesando...",
                      "SearchPlaceholder": "Comience a teclear...",
                      "paginate": {
                          "previous": "Anterior",
                          "next": "Siguiente",
                           }

                }

               }


    );
} );



$('#exampleModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var recipient = button.data('whatever') // Extract info from data-* attributes
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  var modal = $(this)
  modal.find('.modal-title').text('New message to ' + recipient)
  modal.find('.modal-body input').val(recipient)
})
</script>

{% endblock %}

Nismed V0.2/NISMed/templates/turno/modal.html
{% extends "base_turno.html" %}

<div class="modal-dialog modal-lg">
    <div class="modal-content">

              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel">Item</h4>
              </div>
              <div class="modal-body">
                hola hola
              </div>
              <div class="modal-footer">
                <input type="button" class="btn btn-default" data-dismiss="modal" value="annulla" />
                <input type="submit" class="btn btn-primary" value="save" style="margin-bottom: 5px;" />
              </div>

        <script>
            jQuery('.modal-content .calendar').datepicker({ dateFormat: "yy-mm-dd" });

                var form_options = {
                    target: '#modal',
                    success: function() {  }
                }
                $('#item_update_form').ajaxForm(form_options);
        </script>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

Nismed V0.2/NISMed/templates/turno/revisar_planes.html
{% extends "base_turno.html" %}
{% load mathfilters %}





{% block title %}Revision de planes y pendientes{% endblock %}
{% block content %}
<hr>
<div class= "row ">
<div class="col-sm-1 btn">
</div>
<h1>Revisión planes y pendientes</h1>
</div>
<hr>
<br>

{% if Turno %}


<div class="container-fluid">
<div class="row">



    {% if ok == 'no'%}
    <div class="col-5">
<font style= "color: red ; text-align: center; background-color: grey"><h5>No se permitirá cerrar turno hasta que todos los pacientes cuenten con un detalle de  Planes y Pendientes </h5></font>
  </div>
{% else %}

<div class="col-1">
  </div>
<div class="col-4">
<a href="{% url "crear_resumen" Turno.0.id %} " title= "Refrescar"><button type="button" class="btn btn-danger">Cerrar turno</button></a>
</div>

{% endif %}


  <div class="col-1">

</div>
  <div class="col-1">
<a href="{% url "revisar_planes"  %} " title= "Refrescar"> <i class="fa fa-undo-alt fa-5x" aria-hidden="true"></i></a>
</div>
<div class="col-4">
  <h2> Fecha de inicio del turno: {{Turno.0.fechaInicio}} </h2>    <h2> Fecha de termino: {{hoy}} </h2>
</div>
</div>
</div>




<br>
<br>
<div class="container-fluid">

<table id="table_id" class="display">
    <thead>
        <tr>

            <th style="text-align: center">Fecha de hospitalización</th>
            <th style="text-align: center">Paciente</th>
            <th style="text-align: center" >RUT</th>
            <th style="text-align: center">Fecha ultimo control</th>
            <th style="text-align: center" >Planes y pendientes</th>

            <th style="text-align: center" >Opciones</th>

        </tr>
    </thead>
    <tbody>

  {% if Hospitalizacion %}
             {% for i in Hospitalizacion %}

        <tr>

          <td style="text-align: center" >{{i.fechaInicio}} </td>

            <td style="text-align: center" >{{i.evento.paciente.nombres}} {{i.evento.paciente.primerApellido}} {% if i.evento.paciente.segundoApellido %} {{i.evento.paciente.segundoApellido}}  {% endif %}</td>

            <td style="text-align: center">{% if i.evento.paciente.RUT %} {{i.evento.paciente.RUT}}-{{i.evento.paciente.DV}}{% else %} <font style = "color: red"> dato faltante </font> {% endif %}</td>


            <td style="text-align: center">

              {% if i.control_set.all.0 %}

               {{ i.control_set.all.last.fecha }}

               {% endif %}

            </td>


            <td style="text-align: center" >
              {% if i.control_set.all.0 %}

              {% if i.control_set.all.last.planesPendiente  %}  {{ i.control_set.all.last.planesPendiente }}{% else %} <font style = "color: red"> No posee planes y pendientes </font> {% endif %}

              {% endif %}
            </td>






                       <td style="text-align: center" >

                         {% with i.control_set.last as c %}




                          <a title="Crear planes" href="" onclick="return popitupP('{% url "crear_planes" c.id %}')"><i class="far fa-plus-square"> </i></a>


                         {% endwith %}



                       </td>






        </tr>

        {% endfor %}


       {% endif %}


    </tbody>
    <tfoot>
      <tr>

          <th style="text-align: center" >Fecha de hospitalización</th>
          <th style="text-align: center" >Paciente</th>
          <th style="text-align: center" >RUT</th>
          <th style="text-align: center" >Fecha ultimo control</th>
          <th style="text-align: center" >Planes y pendientes</th>

          <th style="text-align: center" >Opciones</th>

      </tr>
    </tfoot>

</table>


</div>



{% else %}

<div class="container-fluid">
<div class="col-12">
<div class="row"> <h1>Lo sentimos, no se encuentra registro de turno activo, por favor cree un nuevo turno </h1></div>
</div>
</div>

{% endif %}








<!-- Button trigger modal -->
<!--  Launch demo modal
</button>-->

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>











 <script type="text/javascript">



  $(document).ready( function () {
    $('#table_id').DataTable(

      {
                  "language":{
                      "lengthMenu":"Mostrar _MENU_ registros por página.",
                      "zeroRecords": "Lo sentimos, no se han registrado hospitalizaciones dentro del turno.",
                      "info": "Mostrando página _PAGE_ de _PAGES_",
                      "infoEmpty": "No se ha encontrado coincidencia.",
                      "infoFiltered": "(filtrados de un total de _MAX_ registros)",
                      "search" : "Buscar",
                      "LoadingRecords": "Cargando ...",
                      "Processing": "Procesando...",
                      "SearchPlaceholder": "Comience a teclear...",
                      "paginate": {
                          "previous": "Anterior",
                          "next": "Siguiente",
                           }

                }

               }


    );
} );



$('#exampleModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var recipient = button.data('whatever') // Extract info from data-* attributes
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  var modal = $(this)
  modal.find('.modal-title').text('New message to ' + recipient)
  modal.find('.modal-body input').val(recipient)
})
</script>

{% endblock %}

Nismed V0.2/NISMed/templates/turno/turno_cerrado.html
{% extends "base_turno.html" %}

{% load staticfiles %}


{% block title %}Turno cerrado{% endblock %}

{% block content %}


<div class="container-fluid">


<br>
<br>
<div class = "row" >

  <div class="col-sm-1 btn">
  </div>

  <div class="col-sm-1 btn">
  </div>
  <h1>Turno cerrado con éxito, descargue el informe en el siguiente link:</h1>  &nbsp;&nbsp;&nbsp;&nbsp; <a href="{% url "informe_turno"  %} " title= "Descargar informe de turno"> <i class="far fa-file-pdf fa-3x" aria-hidden="true"></i></a>
</div>
<br>
<br>


     {% endblock %}